
tunable_params:
  start_position         : [90.0, 5.0] 
  goal_position          : [30.0, 5.0] 
  init_heading            : 135 
  search_angle            : 15.0   
  way_points_distance     : 10.0   
  turning_radius          : 2.0   

obstacle_params:  
  min_dist_threshold_local_grid         : 1.2 
  distance_to_extende_polygons          : 1.4 
  buffer_distance                       : 2.0
  square_dia                            : 0.4 
  max_generation                        : 18
  line_buffer_dist                      : 1.0
  dist_moved_from_salient_points        : 2.0
  show_all_plot                         : False 
  show_graph_bitmap                     : False
  show_graph                            : False     
  graph_length_reduction_iter           : 3  
 
  total_area:
    - [0, 0] 
    - [100, 100] 

  strips:
    - [[54, 40], [70, 40]]
    - [[70, 40], [54, 40]]
    - [[20, 70], [35, 85]]
    - [[35, 85], [20, 70]]
    - [[70, 90], [90, 88]]
    - [[90, 88], [70, 90]]
 
# Obstacle    
  polygon_1: 
    - [77, 18]
    - [85, 18]
    - [85, 27]
    - [77, 27]


  polygon_2:

    - [55, 77]
    - [60, 68]
    - [65, 78]
    - [60, 92]
    
  polygon_3: 
    - [40, 28] 
    - [35, 25]
    - [42, 12]
    - [45, 14] 
